### PR TITLE
jmpi 701 update GitHub actions pipelines

### PR DESCRIPTION
**Pull request by issambaccouch**

### CODE REVIEW

**Comment by walisc** [comment]
Nice @issambaccouch! Are there anymore changes you are going to add to this, or is it ready to be merged?

**Comment by issambaccouch** [comment]
> Nice @issambaccouch! Are there anymore changes you are going to add to this, or is it ready to be merged?

it is ready to be merged but triggered only on the default branch.

**Comment by walisc** [comment]
> > Nice @issambaccouch! Are there anymore changes you are going to add to this, or is it ready to be merged?
> 
> @walisc it is ready to be merged but triggered only on the default branch.

Hi @issambaccouch . What do you mean by 'triggered only on the default branch'?

**Comment by issambaccouch** [comment]
> > > Nice @issambaccouch! Are there anymore changes you are going to add to this, or is it ready to be merged?
> > 
> > 
> > @walisc it is ready to be merged but triggered only on the default branch.
> 
> Hi @issambaccouch . What do you mean by 'triggered only on the default branch'? Do you mean it only triggered on pull requests to the `jembi-base` branch?

The workflow file should be present on the default branch of the repository in order to run.
More information : 
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#about-workflow-triggers

**Comment by walisc** [comment]
> > > > Nice @issambaccouch! Are there anymore changes you are going to add to this, or is it ready to be merged?
> > > 
> > > 
> > > @walisc it is ready to be merged but triggered only on the default branch.
> > 
> > 
> > Hi @issambaccouch . What do you mean by 'triggered only on the default branch'? Do you mean it only triggered on pull requests to the `jembi-base` branch?
> 
> The workflow file should be present on the default branch of the repository in order to run.In our case is 'main' branch More information : https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#about-workflow-triggers

Hi @issambaccouch . Thanks for this. Looks good! Let me know if you want me to merge it, or @ajinkyagadewar / @w-hayes  can 👍🏽

**Pull request merged**
